In [1]:
# Text Based RNN
import numpy as np
import tensorflow as tf


In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN,Dense,Embedding


In [27]:
text=["i love machine learning","i love deep learing","python code","deep learing is powerful","ai is like human"]


In [28]:
tokenizer=Tokenizer()

In [29]:
tokenizer.fit_on_texts(text)

In [30]:
tokenizer

In [31]:
total_words=len(tokenizer.word_index)+1

In [33]:
total_words

14

In [47]:
# input_sequence=[]
# for line in text:
#     token_list=tokenizer.texts_to_sequences([line])[0]
#     for i in range(1,len(token_list)):
#         n_gram=token_list[:i+1]
# input_sequence.append(n_gram)
# input_sequence


input_sequence = []

for line in text:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram = token_list[:i+1]
        input_sequence.append(n_gram)   # 👈 यह line अंदर होनी चाहिए


I Love Machine Learning
I              1
Love           2
Machine        3
Learning       4
Deep           5
Python         6
Code           7
is             8
powerful       9
[1 2 3 4]
[1 2 5 4]
I    Love
I  Love Machine

i               [0,0,1]
I love          [0,1,2]
I Love Machine  [1,2,3]


In [48]:
#Pad sequence

max_len=max(len(seq) for seq in input_sequence)
input_sequence=pad_sequences(input_sequence,maxlen=max_len,padding='pre')


In [49]:
#Split Inot X and Y
X=input_sequence[:, :-1]
y=input_sequence[:, -1]
y


array([ 2,  6,  7,  2,  3,  4,  9,  4,  5, 10,  5, 12, 13], dtype=int32)

In [50]:
model=Sequential([Embedding(total_words,10,input_length=max_len-1),SimpleRNN(32),Dense(total_words,activation='softmax')])

In [51]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [52]:
#Train
model.fit(X,y,epochs=300,verbose=1)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.1538 - loss: 2.6243
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.1538 - loss: 2.6160
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.2308 - loss: 2.6076
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.3077 - loss: 2.5991
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.3846 - loss: 2.5906
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.3846 - loss: 2.5818
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.3846 - loss: 2.5729
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.3846 - loss: 2.5638
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.3846 - loss: 2.5545
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.3846 - loss: 2.5450
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.3846 - loss: 2.5351
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - accuracy: 0.

In [57]:
# Prediction Next 
seed_text="python"
sequence=tokenizer.texts_to_sequences([seed_text])[0]
sequence=pad_sequences([sequence],maxlen=max_len-1,padding='pre')
prediction=model.predict(sequence,verbose=1)
predicted_word=""
for word,index in tokenizer.word_index.items():
    if np.argmax(prediction)==index:
        predicted_word=word
        break
print("Input",seed_text)
print("Next Word",predicted_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
Input python
Next Word code


In [56]:
seed_text = "i love"
sequence = tokenizer.texts_to_sequences([seed_text])[0]
sequence = pad_sequences([sequence], maxlen=max_len-1, padding='pre')
prediction = model.predict(sequence, verbose=0)


predicted_index = np.argmax(prediction)
predicted_word = tokenizer.index_word[predicted_index]

print("Input:", seed_text)
print("Next Word:", predicted_word)


Input: i love
Next Word: machine
